# Based on Redis
FROM redis:6.2.1

# Constants
ENV BUILD_HOME=/opt

# Prepare some folders
RUN mkdir $BUILD_HOME/code
RUN mkdir $BUILD_HOME/modules
RUN mkdir $BUILD_HOME/creds

## Get the sourc code
COPY redisai $BUILD_HOME/code/RedisAI
COPY redisearch $BUILD_HOME/code/RediSearch
COPY similar-images $BUILD_HOME/code/similar-images

# Install some packages
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y gcc
RUN apt-get install -y make
RUN apt-get install -y python3
RUN apt-get install -y wget
RUN apt-get install -y unzip
RUN apt-get install -y python3-opencv

##### RedisAI ######
WORKDIR $BUILD_HOME/code/RedisAI
## Setup tensorflow etc
RUN ./get_deps.sh cpu
## Install system requirements
WORKDIR $BUILD_HOME/code/RedisAI/opt
RUN ./readies/bin/getpy3
RUN ./system-setup.py
## Build 
WORKDIR $BUILD_HOME/code/RedisAI
RUN ALL=1 make -C opt clean build
## Put binaries in modules folder
RUN cp ./bin/linux-x64-release/src/redisai.so $BUILD_HOME/modules/redisai.so
RUN cp ./bin/linux-x64-release/src/redisai_tensorflow.so $BUILD_HOME/modules/redisai_tensorflow.so

##### RediSearch #####
## Fix/get dependancies
WORKDIR $BUILD_HOME/code/RediSearch/deps
RUN git submodule add -f https://github.com/RedisLabsModules/VectorSimilarity.git
RUN git submodule update --init --recursive
RUN ./readies/bin/getpy2
## Build
WORKDIR $BUILD_HOME/code/RediSearch
RUN make setup
RUN make build 
## Put bin in module folder
RUN cp build/redisearch.so $BUILD_HOME/modules/.

##### similar-images #####
WORKDIR $BUILD_HOME/code/similar-images
RUN pip3 install virtualenv
RUN virtualenv env
RUN  /bin/bash -c "source ./env/bin/activate;pip install -r requirments.txt"
RUN chmod +x run.bash

# Ports
EXPOSE 5000
EXPOSE 6379

# Run Redis
CMD $BUILD_HOME/code/similar-images/run.bash
