---
platform: linux
params:
  DOCKERFILE: similar-images/Dockerfile-concourse
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
run:
  path: build
inputs:
  - name: similar-images
  - name: redisearch-repo
  - name: redisai-repo
outputs:
  - name: image